export const transcript = [
    "Good morning! Thank you for coming in today.",
    "Let's start with a classic question: Can you tell me a bit about yourself and your professional background?",
    "Sure, I have a degree in marketing and have worked in the industry for the past five years.",
    "I've managed several successful campaigns and have experience with both digital and traditional marketing strategies.",
    "That's great to hear.",
    "Can you share a specific example of a campaign you managed that you're particularly proud of?",
    "Absolutely.",
    "One campaign I'm proud of is a social media campaign for a product launch.",
    "We utilized various platforms to create buzz, and it resulted in a 30% increase in product sales within the first month.",
    "Impressive! It sounds like you've had some significant successes.",
    "Now, moving on to teamwork, can you give me an example of a challenging situation you faced while working in a team and how you handled it?",
    "Certainly.",
    "There was a project where there was a disagreement within the team regarding the creative direction.",
    "I facilitated a team meeting to discuss everyone's perspectives and found a compromise that satisfied everyone.",
    "Good to know that you can handle conflicts effectively.",
    "Now, looking at your resume, I noticed a gap between your last two positions.",
    "Can you explain that?",
    "Yes, during that time, I took a break to focus on personal development and pursue some freelance projects.",
    "It was a valuable experience that allowed me to gain new skills and perspectives.",
    "Interesting choice.",
    "It's great that you took the initiative for personal development.",
    "Moving on, how do you stay updated with the latest trends and changes in the marketing industry?",
    "I regularly read industry blogs, attend webinars, and participate in networking events to stay informed about the latest trends and updates in marketing.",
    "That's commendable.",
    "One last question before we wrap up.",
    "Where do you see yourself in the next five years?",
    "I see myself in a leadership role, perhaps leading a marketing team or even taking on a broader strategic role within the company.",
    "Thank you for sharing that.",
    "We'll be in touch soon.",
    "It was great getting to know you.",
    "Thank you for having me.",
    "I look forward to the possibility of working together."
]