export const transcript = [
    "Hello and welcome!",
    "Let's start with a common question.",
    "Can you walk me through your resume and highlight the skills and experiences that make you a strong candidate for this position?",
    "Hi there!",
    "Certainly",
    "I have a background in sales and have been in the industry for about seven years",
    "I've consistently met and exceeded sales targets, developed strong client relationships, and have a proven track record of driving revenue growth",
    "That's impressive",
    "Can you tell me about a specific challenging situation you faced in your previous role and how you handled it?",
    "Of course",
    "There was a situation where a key client was considering switching to a competitor",
    "I proactively reached out to the client, addressed their concerns, and managed to retain their business by offering personalized solutions",
    "It sounds like you're adept at handling challenges",
    "Now, looking at your resume, I noticed a gap between your first and second job",
    "Could you explain that gap?",
    "Yes, during that time, I was exploring different career paths and took on some freelance projects to broaden my skills",
    "It was a period of self-discovery and personal growth",
    "Interesting",
    "It's good that you took the initiative to explore and develop new skills",
    "Now, let's talk about teamwork",
    "Can you share an example of a time when you faced difficulties working with a team member, and how did you resolve it?",
    "Certainly",
    "There was a project where collaboration was essential, but a team member wasn't pulling their weight",
    "I addressed the issue directly with them, identified the root cause, and we worked together to find a solution that improved our collaboration",
    "Handling conflicts directly is crucial",
    "Moving on, can you share an experience where you had to adapt to a sudden change in priorities or unexpected challenges?",
    "Yes, in my previous role, there was a sudden shift in the market that required us to pivot our sales strategy",
    "I quickly adapted by re-evaluating our approach, identifying new opportunities, and implementing changes that resulted in continued success",
    "That's a valuable skill",
    "Finally, where do you see yourself in the next five years?",
    "I envision myself in a leadership role, possibly managing a sales team or contributing to the strategic direction of the company",
    "Thank you for sharing that",
    "We'll be in touch soon",
    "It was great meeting you",
    "Thank you",
    "I appreciate the opportunity and look forward to the next steps"
];