export const transcript = [
    "¡Hola! ¿Has viajado a algún lugar emocionante recientemente?",
    "Sí, fui a México el verano pasado. ¡Fue una experiencia increíble!",
    "¡Guau! Me encantaría ir a México. ¿Qué lugares visitaste?",
    "Visitamos Ciudad de México, Cancún y Chichen Itzá. ¡Chichen Itzá es asombroso!",
    "Debes haber tomado muchas fotos allí. ¿Has probado la comida mexicana auténtica?",
    "Sí, probé los tacos y el guacamole. ¡Todo estaba delicioso!",
    "¡Suena delicioso! ¿Tuviste algún problema con el idioma?",
    "Un poco. A veces, la gente hablaba muy rápido y me perdía en la conversación.",
    "Sí, eso me pasó en España también. ¿Cómo te movías por la ciudad?",
    "Tomamos el metro y también usamos Uber. Fue conveniente y seguro.",
    "Eso es genial. ¿Encontraste alguna tradición interesante durante tu viaje?",
    "Sí, presenciamos una celebración local con bailes y música tradicional. Fue hermoso.",
    "Debe haber sido una experiencia única. ¿Te gustaría volver a México?",
    "Definitivamente. Quiero explorar más lugares y conocer la cultura a fondo.",
    "Es una buena idea. ¿Tienes algún destino soñado para tu próximo viaje?",
    "Me encantaría visitar Japón. Siempre he querido experimentar la cultura japonesa.",
    "¡Oh, eso suena increíble! Desde el sushi hasta los templos antiguos, todo es fascinante.",
    "Exacto. ¿Tienes algún consejo para planificar un viaje exitoso?",
    "Sí, investiga bien antes de ir, aprende algunas frases básicas del idioma local y sé flexible con tu itinerario.",
    "Gracias por los consejos. Definitivamente los tendré en cuenta para mi próximo viaje.",
    "De nada. ¡Espero que tengas un viaje tan increíble como el mío!",
    "¡Gracias! Estoy emocionado. ¿Tienes alguna otra anécdota divertida de tu viaje a México?",
    "Oh, sí. Una vez intenté bailar salsa con los lugareños y fue un desastre. ¡Pero todos se divirtieron!",
    "¡Eso suena divertido! A veces, las mejores experiencias son las inesperadas. ¿Qué te llevas de México?",
    "Recuerdos inolvidables y la esperanza de regresar algún día. ¡Fue un viaje asombroso!",
    "¡Qué maravilloso! Gracias por compartir tu experiencia de viaje conmigo.",
    "De nada. Siempre es divertido hablar de aventuras. ¿Tú tienes algún viaje planeado?",
    "Sí, estoy planeando ir a Italia el próximo año. ¡Estoy emocionado!",
    "¡Italia es increíble! ¡Disfruta de tu viaje y de la deliciosa comida italiana!",
    "Gracias, lo haré. ¡Hablamos después sobre nuestras experiencias de viaje!",
    "¡Claro! ¡Buen viaje y hasta luego!"
];
