export const transcript = [
    "Greetings! Thank you for joining us today.",
    "Let's kick off with a standard opening question.",
    "Could you provide an overview of your professional background and what motivated you to apply for this position?",
    "Hello! Certainly.",
    "I come from a project management background with a focus on IT projects for the past eight years.",
    "I've successfully led cross-functional teams, ensuring projects are delivered on time and within budget.",
    "Great track record.",
    "Can you share a specific project where you faced a tight deadline and how you managed to meet it?",
    "Absolutely.",
    "There was a project with a strict deadline due to external factors.",
    "I implemented agile methodologies, streamlined communication, and the team worked overtime, resulting in the successful delivery of the project ahead of schedule.",
    "Efficient project management is crucial.",
    "Looking at your resume, I see you have experience with project management software.",
    "Can you elaborate on your proficiency with a specific tool mentioned in the job description?",
    "Certainly.",
    "I've extensively used Jira for project tracking and collaboration.",
    "In one project, we customized workflows in Jira, which improved task visibility and reduced project completion time by 15%.",
    "That's a practical application.",
    "Now, let's talk about a challenge you faced in stakeholder management.",
    "Can you share an example of a situation where you had to navigate conflicting stakeholder priorities?",
    "Of course.",
    "I worked on a project where marketing and development had conflicting priorities.",
    "I facilitated a workshop to align goals, and we established a clear roadmap that satisfied both teams.",
    "Effective stakeholder management is key.",
    "Lastly, how do you handle stress and tight deadlines in a fast-paced environment?",
    "I thrive in fast-paced environments by prioritizing tasks, maintaining open communication, and ensuring the team is well-supported.",
    "Good to know.",
    "Thank you for sharing your experiences.",
    "We'll be in touch soon."
];
