export const transcript = [
    "Hello and thank you for being here today!",
    "Let's dive into your background.",
    "Can you walk me through your resume and highlight your skills and experiences relevant to this role?",
    "Absolutely.",
    "I've been working in software development for the past five years.",
    "I've been involved in various projects, from developing web applications to optimizing database performance.",
    "One notable project was implementing a new feature that significantly improved user engagement and reduced load times.",
    "That sounds like valuable experience.",
    "Can you share a specific technical challenge you faced in your previous role and how you tackled it?",
    "Certainly.",
    "We encountered a scalability issue where the application couldn't handle increased user traffic during peak hours.",
    "I led a team to refactor the codebase, implemented caching strategies, and optimized database queries, resulting in a 40% improvement in overall system performance.",
    "Impressive problem-solving skills.",
    "Now, let's discuss your familiarity with certain technologies mentioned in the job description.",
    "I noticed you listed experience with React in your resume.",
    "Can you elaborate on a project where you utilized React and the impact it had?",
    "Yes, I've worked on a large-scale e-commerce platform where we implemented React for the frontend.",
    "This improved the user interface, resulting in a 20% increase in user interactions and overall customer satisfaction.",
    "Great to hear.",
    "Moving on, this role requires collaboration with cross-functional teams.",
    "Can you share an example of a project where you had to work closely with non-technical stakeholders?",
    "Certainly.",
    "I collaborated with the marketing team on a website redesign project.",
    "I had to explain technical concepts in a non-technical way, ensuring alignment between the design and functionality.",
    "Effective communication is crucial.",
    "Finally, where do you see the future of software development, and how do you plan to stay ahead of industry trends?",
    "I believe the future lies in artificial intelligence and machine learning integration.",
    "I stay updated by participating in online forums, attending conferences, and engaging in continuous learning.",
    "That's a forward-thinking perspective.",
    "Thank you for sharing your experiences and insights.",
    "We'll be in touch soon."
];
